version: '3.8'
services:
  comfort-player:
    image: ghcr.io/rittme/comfort-player:latest
    container_name: comfort-player
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MEDIA_DIR=/app/media
      - SEASONS_DIR=/app/media/shows
      - STATE_FILE=/app/data/state.json
      - API_KEY=${API_KEY:-your-secret-token}
      - VIDEO_FILE_PATTERN=*.mp4,*.mkv,*.avi
      - SUBTITLE_FILE_PATTERN=*.srt,*.vtt
    volumes:
      - ./media:/app/media:ro # Mount media folder as external volume
      - ./data:/app/data # Mount data folder as external volume for persistent state
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/show/info"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
